server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: yeon
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create -> 프로젝트를 실행할 때마다 table을 새로 만들겠다는 의미. 따라서 프로젝트 최초 실행 후에는 update로 변경해야 함
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #entity(table)을 만들 때 변수명 그대로 데이터베이스에 넣어준다는 의미
      use-new-id-generator-mappings: false #jpa가 사용하는 전략을 따라가지 않겠다. -> false / 따라가겠다 -> true
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
    
    